### ISSUE TITLE
dx: consider make verbose flag more functional

### ISSUE THREAD

**Issue by Dentrax** [kondukto-io/kdt#37]
Currently, if we get an error, it's quite a bit hard to diagnose the error that threw.

```
$ kdt scan --tool trivy --image busybox --verbose

2021/05/18 16:10:33 could not start scan: HTTP response not OK
```

instead of, we can print API requests and status codes, i.e.:
```
2021/05/18 16:10:33 calling api/v1/etc/...
2021/05/18 16:10:33 got timeout after 3 retries
2021/05/18 16:10:33 could not start scan: HTTP response not OK
2021/05/18 16:10:33 HTTP status code: 500
...
...
...
```

Wdyt?

**Comment by sbalka** [comment]
Thanks for the feedback @Dentrax. I agree that KDT needs improvements in verbosity and error messages. We have started working on this issue and the updates will be included in the upcoming releases. When the release is ready, we'll update this issue and notify you to get the latest updates.
